/**
 * Deterministic 3-day clinical program review rules.
 * High pain (>8) → catalog swap (same area/muscle, lower difficulty) or reduce;
 * Low pain + steady adherence → catalog progression swap or load bump;
 * Else maintain.
 * Timing: 7-day new-patient grace; 3-day cooldown after therapist decline.
 *
 * CANONICAL SOURCE — Edge copy is generated by:
 *   npm run sync:program-review-engine
 * Do not edit `supabase/functions/_shared/programReviewEngine.ts` by hand.
 */

export const PROGRAM_REVIEW_WINDOW_DAYS = 3;
export const NEW_PATIENT_GRACE_DAYS = 7;
export const REJECTION_COOLDOWN_DAYS = 3;
export const HIGH_PAIN_THRESHOLD = 8;
export const LOW_PAIN_THRESHOLD = 3;
export const STEADY_ADHERENCE_MIN = 0.75;

export type ProgramReviewDecision = 'reduce' | 'progress' | 'maintain';

export type ProgramReviewExerciseInput = {
  id: string;
  name: string;
  sets: number;
  reps: number;
  holdSeconds?: number | null;
  difficulty?: number;
  targetArea?: string;
  muscleGroup?: string;
  clinicalRegressionHint?: string | null;
  clinicalProgressionHint?: string | null;
};

export type ProgramReviewPainSample = {
  exerciseId: string;
  painLevel: number;
  sessionDate: string;
};

export type ProgramReviewCatalogCandidate = {
  id: string;
  name: string;
  sets: number;
  reps: number | null;
  holdSeconds: number | null;
  difficulty: number;
  targetArea: string;
  muscleGroup: string;
  clinicalRegressionHint?: string | null;
  clinicalProgressionHint?: string | null;
};

export type ProposedExerciseChange = {
  exerciseId: string;
  exerciseName: string;
  action:
    | 'reduce_reps'
    | 'reduce_sets'
    | 'swap'
    | 'progress_swap'
    | 'progress_reps'
    | 'progress_sets'
    | 'keep';
  fromSets: number;
  toSets: number;
  fromReps: number;
  toReps: number;
  swapToExerciseId?: string;
  swapToExerciseName?: string;
  noteHebrew: string;
};

export type ProgramReviewEngineResult = {
  decision: ProgramReviewDecision;
  rationaleHebrew: string;
  metrics: {
    avgPain: number | null;
    maxPain: number | null;
    adherenceRate: number | null;
    logDays: number;
    highPainExerciseIds: string[];
    catalogDrivenSwaps: number;
  };
  proposedChanges: ProposedExerciseChange[];
  proposedExercises: Array<Record<string, unknown>>;
};

function clampInt(n: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, Math.round(n)));
}

function mean(nums: number[]): number | null {
  if (nums.length === 0) return null;
  return nums.reduce((s, n) => s + n, 0) / nums.length;
}

function maxOf(nums: number[]): number | null {
  if (nums.length === 0) return null;
  return Math.max(...nums);
}

/** Parse YYYY-MM-DD → local midnight Date (calendar math only). */
export function parseYmd(ymd: string): Date {
  const [y, m, d] = ymd.slice(0, 10).split('-').map((x) => parseInt(x, 10));
  return new Date(y, m - 1, d);
}

/** Whole calendar days from a → b (b - a). */
export function clinicalDayDiff(fromYmd: string, toYmd: string): number {
  const a = parseYmd(fromYmd).getTime();
  const b = parseYmd(toYmd).getTime();
  return Math.round((b - a) / (24 * 60 * 60 * 1000));
}

function normalizeKey(s: string | undefined | null): string {
  return (s ?? '').trim().toLowerCase();
}

function sameAreaOrMuscle(
  current: ProgramReviewExerciseInput,
  candidate: ProgramReviewCatalogCandidate
): boolean {
  const area = normalizeKey(current.targetArea);
  const muscle = normalizeKey(current.muscleGroup);
  const cArea = normalizeKey(candidate.targetArea);
  const cMuscle = normalizeKey(candidate.muscleGroup);
  if (area && cArea && area === cArea) return true;
  if (muscle && cMuscle && muscle === cMuscle) return true;
  // Catalog often stores Hebrew muscle labels matching exercise.muscleGroup
  if (area && cMuscle && (cMuscle.includes(area) || area.includes(cMuscle))) return true;
  if (muscle && cArea && (muscle.includes(cArea) || cArea.includes(muscle))) return true;
  return false;
}

function catalogMatchScore(
  current: ProgramReviewExerciseInput,
  candidate: ProgramReviewCatalogCandidate
): number {
  let score = 0;
  if (
    normalizeKey(current.targetArea) &&
    normalizeKey(current.targetArea) === normalizeKey(candidate.targetArea)
  ) {
    score += 2;
  }
  if (
    normalizeKey(current.muscleGroup) &&
    normalizeKey(current.muscleGroup) === normalizeKey(candidate.muscleGroup)
  ) {
    score += 2;
  }
  return score;
}

/** Safer / lower-difficulty catalog alternative — same muscle group or target area. */
export function pickRegressionSwap(
  current: ProgramReviewExerciseInput,
  catalog: ProgramReviewCatalogCandidate[],
  usedIds: Set<string>
): ProgramReviewCatalogCandidate | null {
  const difficulty = current.difficulty ?? 2;
  const candidates = catalog
    .filter(
      (c) =>
        c.id !== current.id &&
        !usedIds.has(c.id) &&
        sameAreaOrMuscle(current, c) &&
        c.difficulty < difficulty
    )
    .sort(
      (a, b) =>
        catalogMatchScore(current, b) - catalogMatchScore(current, a) ||
        a.difficulty - b.difficulty ||
        a.name.localeCompare(b.name)
    );
  return candidates[0] ?? null;
}

/** Advanced catalog alternative — same muscle group or target area, higher difficulty. */
export function pickProgressionSwap(
  current: ProgramReviewExerciseInput,
  catalog: ProgramReviewCatalogCandidate[],
  usedIds: Set<string>
): ProgramReviewCatalogCandidate | null {
  const difficulty = current.difficulty ?? 2;
  const candidates = catalog
    .filter(
      (c) =>
        c.id !== current.id &&
        !usedIds.has(c.id) &&
        sameAreaOrMuscle(current, c) &&
        c.difficulty > difficulty
    )
    .sort(
      (a, b) =>
        catalogMatchScore(current, b) - catalogMatchScore(current, a) ||
        a.difficulty - b.difficulty ||
        a.name.localeCompare(b.name)
    );
  return candidates[0] ?? null;
}

export type EvaluateProgramReviewInput = {
  exercises: ProgramReviewExerciseInput[];
  painSamples: ProgramReviewPainSample[];
  daysWithWork: number;
  adherenceRate: number | null;
  catalog?: ProgramReviewCatalogCandidate[];
};

/**
 * Pure rule engine — never auto-applies; callers persist as proposals for therapist approval.
 * Catalog-driven swaps are preferred over sets/reps tweaks when a suitable catalog row exists.
 */
export function evaluateProgramReview(input: EvaluateProgramReviewInput): ProgramReviewEngineResult {
  const { exercises, painSamples, daysWithWork, adherenceRate, catalog = [] } = input;
  const painLevels = painSamples.map((p) => p.painLevel);
  const avgPain = mean(painLevels);
  const maxPain = maxOf(painLevels);

  const painByExercise = new Map<string, number[]>();
  for (const sample of painSamples) {
    const arr = painByExercise.get(sample.exerciseId) ?? [];
    arr.push(sample.painLevel);
    painByExercise.set(sample.exerciseId, arr);
  }

  const highPainExerciseIds: string[] = [];
  for (const [exerciseId, levels] of painByExercise) {
    if (levels.some((p) => p > HIGH_PAIN_THRESHOLD)) {
      highPainExerciseIds.push(exerciseId);
    }
  }

  const usedSwapIds = new Set<string>(exercises.map((e) => e.id));
  const proposedChanges: ProposedExerciseChange[] = [];
  const proposedExercises: Array<Record<string, unknown>> = [];
  let catalogDrivenSwaps = 0;

  const needsReduce = highPainExerciseIds.length > 0;
  const steadyProgress =
    !needsReduce &&
    daysWithWork >= PROGRAM_REVIEW_WINDOW_DAYS &&
    (avgPain == null || avgPain <= LOW_PAIN_THRESHOLD) &&
    (adherenceRate == null || adherenceRate >= STEADY_ADHERENCE_MIN);

  let decision: ProgramReviewDecision = 'maintain';
  if (needsReduce) decision = 'reduce';
  else if (steadyProgress) decision = 'progress';

  for (const ex of exercises) {
    const base = {
      fromSets: ex.sets,
      toSets: ex.sets,
      fromReps: ex.reps,
      toReps: ex.reps,
    };
    const isHigh = highPainExerciseIds.includes(ex.id);

    if (decision === 'reduce' && isHigh) {
      const swap = pickRegressionSwap(ex, catalog, usedSwapIds);
      if (swap) {
        usedSwapIds.add(swap.id);
        catalogDrivenSwaps++;
        proposedChanges.push({
          exerciseId: ex.id,
          exerciseName: ex.name,
          action: 'swap',
          ...base,
          toSets: swap.sets,
          toReps: swap.reps ?? ex.reps,
          swapToExerciseId: swap.id,
          swapToExerciseName: swap.name,
          noteHebrew:
            ex.clinicalRegressionHint?.trim() ||
            `כאב מעל ${HIGH_PAIN_THRESHOLD}/10 — החלפה מקטלוג לתרגיל בטוח יותר (קושי ${swap.difficulty}) באותו אזור/קבוצת שריר.`,
        });
        proposedExercises.push({
          id: swap.id,
          name: swap.name,
          sets: swap.sets,
          reps: swap.reps ?? ex.reps,
          holdSeconds: swap.holdSeconds,
          difficulty: swap.difficulty,
          targetArea: swap.targetArea,
          muscleGroup: swap.muscleGroup,
          patientSets: swap.sets,
          patientReps: swap.reps ?? ex.reps,
          clinicalRegressionHint: swap.clinicalRegressionHint,
          clinicalProgressionHint: swap.clinicalProgressionHint,
          replacedExerciseId: ex.id,
        });
        continue;
      }
      // Fallback only when catalog has no safer alternative.
      const nextReps = ex.reps > 0 ? clampInt(ex.reps * 0.7, 1, ex.reps - 1 || 1) : ex.reps;
      const nextSets = ex.reps > 0 ? ex.sets : clampInt(ex.sets - 1, 1, ex.sets);
      const action = ex.reps > 0 ? ('reduce_reps' as const) : ('reduce_sets' as const);
      proposedChanges.push({
        exerciseId: ex.id,
        exerciseName: ex.name,
        action,
        fromSets: ex.sets,
        toSets: action === 'reduce_sets' ? nextSets : ex.sets,
        fromReps: ex.reps,
        toReps: action === 'reduce_reps' ? nextReps : ex.reps,
        noteHebrew:
          ex.clinicalRegressionHint?.trim() ||
          `כאב מעל ${HIGH_PAIN_THRESHOLD}/10 — לא נמצא תרגיל חלופי בקטלוג; מוצע להפחית עומס עד לאישור המטפל.`,
      });
      proposedExercises.push({
        id: ex.id,
        name: ex.name,
        patientSets: action === 'reduce_sets' ? nextSets : ex.sets,
        patientReps: action === 'reduce_reps' ? nextReps : ex.reps,
        sets: action === 'reduce_sets' ? nextSets : ex.sets,
        reps: action === 'reduce_reps' ? nextReps : ex.reps,
        holdSeconds: ex.holdSeconds,
        difficulty: ex.difficulty,
        targetArea: ex.targetArea,
        muscleGroup: ex.muscleGroup,
      });
      continue;
    }

    if (decision === 'progress') {
      const swap = pickProgressionSwap(ex, catalog, usedSwapIds);
      if (swap) {
        usedSwapIds.add(swap.id);
        catalogDrivenSwaps++;
        proposedChanges.push({
          exerciseId: ex.id,
          exerciseName: ex.name,
          action: 'progress_swap',
          ...base,
          toSets: swap.sets,
          toReps: swap.reps ?? ex.reps,
          swapToExerciseId: swap.id,
          swapToExerciseName: swap.name,
          noteHebrew:
            ex.clinicalProgressionHint?.trim() ||
            `התקדמות יציבה — החלפה מקטלוג לתרגיל מתקדם יותר (קושי ${swap.difficulty}) באותו אזור/קבוצת שריר.`,
        });
        proposedExercises.push({
          id: swap.id,
          name: swap.name,
          sets: swap.sets,
          reps: swap.reps ?? ex.reps,
          holdSeconds: swap.holdSeconds,
          difficulty: swap.difficulty,
          targetArea: swap.targetArea,
          muscleGroup: swap.muscleGroup,
          patientSets: swap.sets,
          patientReps: swap.reps ?? ex.reps,
          clinicalRegressionHint: swap.clinicalRegressionHint,
          clinicalProgressionHint: swap.clinicalProgressionHint,
          replacedExerciseId: ex.id,
        });
        continue;
      }
      if (ex.reps > 0) {
        const nextReps = clampInt(ex.reps + 2, ex.reps + 1, 30);
        proposedChanges.push({
          exerciseId: ex.id,
          exerciseName: ex.name,
          action: 'progress_reps',
          fromSets: ex.sets,
          toSets: ex.sets,
          fromReps: ex.reps,
          toReps: nextReps,
          noteHebrew:
            ex.clinicalProgressionHint?.trim() ||
            'התקדמות יציבה — לא נמצא תרגיל מתקדם בקטלוג; מוצע להעלות חזרות (דורש אישור מטפל).',
        });
        proposedExercises.push({
          id: ex.id,
          name: ex.name,
          patientSets: ex.sets,
          patientReps: nextReps,
          sets: ex.sets,
          reps: nextReps,
          holdSeconds: ex.holdSeconds,
          difficulty: ex.difficulty,
          targetArea: ex.targetArea,
          muscleGroup: ex.muscleGroup,
        });
      } else {
        const nextSets = clampInt(ex.sets + 1, ex.sets + 1, 5);
        proposedChanges.push({
          exerciseId: ex.id,
          exerciseName: ex.name,
          action: 'progress_sets',
          fromSets: ex.sets,
          toSets: nextSets,
          fromReps: ex.reps,
          toReps: ex.reps,
          noteHebrew:
            ex.clinicalProgressionHint?.trim() ||
            'התקדמות יציבה — לא נמצא תרגיל מתקדם בקטלוג; מוצע להוסיף סט (דורש אישור מטפל).',
        });
        proposedExercises.push({
          id: ex.id,
          name: ex.name,
          patientSets: nextSets,
          patientReps: ex.reps,
          sets: nextSets,
          reps: ex.reps,
          holdSeconds: ex.holdSeconds,
          difficulty: ex.difficulty,
          targetArea: ex.targetArea,
          muscleGroup: ex.muscleGroup,
        });
      }
      continue;
    }

    proposedChanges.push({
      exerciseId: ex.id,
      exerciseName: ex.name,
      action: 'keep',
      ...base,
      noteHebrew: 'שמירה על העומס הנוכחי — אין אינדיקציה לשינוי בחלון 3 הימים.',
    });
    proposedExercises.push({
      id: ex.id,
      name: ex.name,
      patientSets: ex.sets,
      patientReps: ex.reps,
      sets: ex.sets,
      reps: ex.reps,
      holdSeconds: ex.holdSeconds,
      difficulty: ex.difficulty,
      targetArea: ex.targetArea,
      muscleGroup: ex.muscleGroup,
    });
  }

  const metrics = {
    avgPain: avgPain != null ? Math.round(avgPain * 10) / 10 : null,
    maxPain,
    adherenceRate: adherenceRate != null ? Math.round(adherenceRate * 100) / 100 : null,
    logDays: daysWithWork,
    highPainExerciseIds,
    catalogDrivenSwaps,
  };

  let rationaleHebrew: string;
  if (decision === 'reduce') {
    rationaleHebrew =
      `בחלון 3 הימים זוהו דיווחי כאב מעל ${HIGH_PAIN_THRESHOLD}/10` +
      (maxPain != null ? ` (שיא ${maxPain}/10)` : '') +
      (catalogDrivenSwaps > 0
        ? `. הוצעו ${catalogDrivenSwaps} החלפות מקטלוג התרגילים`
        : '. לא נמצאו חלופות בקטלוג — הוצעה הפחתת עומס') +
      ' — ממתין לאישור מטפל לפני עדכון התוכנית.';
  } else if (decision === 'progress') {
    rationaleHebrew =
      'כאב נמוך והשלמה יציבה לאורך 3 ימים — ' +
      (catalogDrivenSwaps > 0
        ? `הוצעו ${catalogDrivenSwaps} התקדמויות מקטלוג התרגילים`
        : 'הוצעה העלאת עומס (ללא חלופת קטלוג מתאימה)') +
      '. כל שינוי דורש אישור מטפל מפורש.';
  } else {
    rationaleHebrew =
      'אין מגמה חריגה בחלון 3 הימים — ממליצים לשמור על התוכנית הנוכחית. רשום לתיעוד מחזור הביקורת.';
  }

  return {
    decision,
    rationaleHebrew,
    metrics,
    proposedChanges,
    proposedExercises,
  };
}

export type ProgramReviewDueInput = {
  clinicalToday: string;
  /** Program start / join date (YYYY-MM-DD). Null = treat as eligible (legacy). */
  programStartYmd: string | null;
  lastReviewWindowEnd: string | null;
  /** Clinical date (YYYY-MM-DD) of the latest therapist decline, if any. */
  lastDeclinedYmd: string | null;
  hasPendingProposal: boolean;
  daysWithLogsInWindow: number;
};

/**
 * Timing gate: never spam after decline; skip first program week; one pending max.
 */
export function isDueForProgramReview(params: ProgramReviewDueInput): boolean {
  if (params.hasPendingProposal) return false;

  if (params.programStartYmd) {
    const daysSinceStart = clinicalDayDiff(params.programStartYmd, params.clinicalToday);
    if (daysSinceStart < NEW_PATIENT_GRACE_DAYS) return false;
  }

  if (params.lastDeclinedYmd) {
    const daysSinceDecline = clinicalDayDiff(params.lastDeclinedYmd, params.clinicalToday);
    if (daysSinceDecline < REJECTION_COOLDOWN_DAYS) return false;
  }

  if (params.lastReviewWindowEnd == null) {
    return params.daysWithLogsInWindow >= PROGRAM_REVIEW_WINDOW_DAYS;
  }

  const daysSinceWindowEnd = clinicalDayDiff(params.lastReviewWindowEnd, params.clinicalToday);
  return daysSinceWindowEnd >= PROGRAM_REVIEW_WINDOW_DAYS;
}

/** Resolve program start from patient payload fields (no PHI). */
export function resolveProgramStartYmd(payload: unknown): string | null {
  if (!payload || typeof payload !== 'object' || Array.isArray(payload)) return null;
  const p = payload as Record<string, unknown>;
  for (const key of ['startDate', 'joinDate', 'surgeryDate']) {
    const v = p[key];
    if (typeof v === 'string' && /^\d{4}-\d{2}-\d{2}/.test(v)) {
      return v.slice(0, 10);
    }
  }
  return null;
}
